# Generated by Django 3.0.7 on 2020-06-09 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mentor',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=4),
        ),
        migrations.AddField(
            model_name='mentor',
            name='display_name',
            field=models.CharField(default='Display Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='fun_facts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=3),
        ),
        migrations.AddField(
            model_name='mentor',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
