# Generated by Django 3.0.5 on 2020-06-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_blogpost_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='blogpost',
            new_name='blogposts',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='blogpost',
            new_name='blogposts',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
