# Generated by Django 3.0.7 on 2020-06-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0008_auto_20200607_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
