# Generated by Django 3.0.7 on 2020-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0010_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('b', 'blogpost'), ('w', 'webinar')], default='b', max_length=1),
        ),
    ]
