# Generated by Django 3.0.7 on 2020-06-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0006_auto_20200607_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='topics_of_interest',
        ),
        migrations.CreateModel(
            name='InterestTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('ApplicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_topic', to='application_form.ApplicationForm')),
            ],
        ),
    ]
