# Generated by Django 3.0.7 on 2020-06-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0007_auto_20200608_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttopic',
            name='ApplicationForm',
        ),
        migrations.AddField(
            model_name='interesttopic',
            name='ApplicationForm',
            field=models.ManyToManyField(related_name='interest_topic', to='application_form.ApplicationForm'),
        ),
    ]
