# Generated by Django 3.0.7 on 2020-06-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20200609_1912'),
        ('school', '0002_auto_20200530_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_directed', to='mentor.Mentor'),
        ),
        migrations.AddField(
            model_name='school',
            name='mentors',
            field=models.ManyToManyField(null=True, related_name='schools_mentored', to='mentor.Mentor'),
        ),
    ]
